import { randomBytes } from 'crypto';
import { accessSync, chmodSync, constants, existsSync, readFileSync, writeFileSync } from 'fs';
import { homedir } from 'os';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ENV_FILE = path.join(ROOT, '.env');
const force = process.argv.includes('--force');

if (existsSync(ENV_FILE) && !force) {
  console.log(`${ENV_FILE} already exists; use --force to replace it.`);
  process.exit(0);
}

const codexHome = path.join(homedir(), '.codex');
const codexConfig = path.join(codexHome, 'config.toml');
const codexBin = findCodexExecutable();
const defaults = readCodexDefaults(codexConfig);
const password = randomBytes(18).toString('base64url');
const secret = randomBytes(48).toString('hex');

const values = {
  APP_NAME: 'Codex Web',
  CODEX_WEB_PASSWORD: password,
  SESSION_SECRET: secret,
  SESSION_TTL_HOURS: '168',
  COOKIE_SECURE: 'false',
  HOST: '127.0.0.1',
  PORT: '36354',
  PUBLIC_HOST: '127.0.0.1',
  PORT_MIN: '30000',
  PORT_MAX: '39999',
  CODEX_BIN: codexBin,
  CODEX_HOME: codexHome,
  CODEX_CONFIG_WRITABLE: 'false',
  CODEX_DESKTOP_IPC_ENABLED: process.platform === 'darwin' || process.platform === 'win32' ? 'true' : 'false',
  CODEX_DESKTOP_IPC_TIMEOUT_MS: '20000',
  NATIVE_SESSION_MAX_READ_MB: '0',
  NATIVE_SESSION_MAX_MESSAGES: '0',
  NATIVE_SESSION_MAX_ITEMS: '100',
  NATIVE_SESSION_POLL_MS: '3000',
  CODEX_WEB_ENV_FILE: ENV_FILE,
  CODEX_WEB_RUNTIME_DIR: path.join(ROOT, 'runtime'),
  DEFAULT_PROVIDER: defaults.provider,
  DEFAULT_MODEL: defaults.model,
  DEFAULT_CWD: path.dirname(ROOT),
  DEFAULT_SANDBOX: 'workspace-write',
  DEFAULT_APPROVAL: 'never',
};

const content = [
  '# Generated by npm run setup. Keep this file local.',
  ...Object.entries(values).map(([key, value]) => `${key}=${formatEnvValue(value)}`),
  '',
].join('\n');

writeFileSync(ENV_FILE, content, { mode: 0o600 });
chmodSync(ENV_FILE, 0o600);

console.log(`Created ${ENV_FILE}`);
console.log(`URL: http://${values.PUBLIC_HOST}:${values.PORT}`);
console.log(`Password: ${password}`);

function findCodexExecutable() {
  const candidates = [
    '/Applications/ChatGPT.app/Contents/Resources/codex',
    '/Applications/Codex.app/Contents/Resources/codex',
    findExecutable('codex'),
  ].filter(Boolean);
  for (const candidate of candidates) {
    try {
      accessSync(candidate, constants.X_OK);
      return candidate;
    } catch {}
  }
  return 'codex';
}

function findExecutable(name) {
  for (const directory of String(process.env.PATH || '').split(path.delimiter)) {
    if (!directory) continue;
    const candidate = path.join(directory, name);
    try {
      accessSync(candidate, constants.X_OK);
      return candidate;
    } catch {}
  }
  return '';
}

function readCodexDefaults(file) {
  if (!existsSync(file)) return { provider: '', model: '' };
  const content = readFileSync(file, 'utf8');
  return {
    provider: content.match(/^model_provider\s*=\s*"([^"]+)"/m)?.[1] || '',
    model: content.match(/^model\s*=\s*"([^"]+)"/m)?.[1] || '',
  };
}

function formatEnvValue(value) {
  const text = String(value || '');
  if (!text) return '';
  if (/^[A-Za-z0-9_./:@+-]+$/.test(text)) return text;
  return JSON.stringify(text);
}
